### ISSUE TITLE
RPi.GPIO dependency

### ISSUE THREAD

**Issue by dubaleeiro** [pimoroni/mopidy-raspberry-gpio#10]
Hello, thanks for this good Mopidy extension !

I spent today a lot of time trying to figure out why it was not work, since I came to the idea of checking whether the RPi.GPIO was installed - it was not.

Could you please mention it in the README.rst ? Maybe there are also not very experienced people like me out there and it would save some time with finding a solution...

Thanks!

**Comment by Gadgetoid** [comment]
Whoops. Sorry.

Added a note to the README. The soft dependency is due to `RPi.GPIO` *normally* being satisfied by `apt` and even more typically pre-installed on Pi's.
