### ISSUE TITLE
Update PyPI/PIP to latest version

### ISSUE THREAD

**Issue by bluepuma77** [pimoroni/mopidy-raspberry-gpio#15]
I just manually installed [mopidy-raspberry-gpio](https://github.com/pimoroni/mopidy-raspberry-gpio) on a brand new [RaspberryPi Zero 2](https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/) with Debian Bullseye and [Mopidy](https://mopidy.com).

After a lot of troubleshooting I looked into the source code `/usr/local/lib/python3.9/dist-packages/mopidy_raspberry_gpio/ext.conf` and found the Pirate Audio default pin config, that [was dropped 17 July 2020](https://github.com/pimoroni/mopidy-raspberry-gpio/commit/b4f6137f65d416ef4f7246023f55219d5a50ddbb) on GitHub.

The latest PyPI/PIP library 1.0.2 was [released two days earlier](https://pypi.org/project/mopidy-raspberry-gpio/#history), so PyPI/PIP is not up to date with the current state on GitHub.

It would be great if PyPI/PIP could be updated. I was assuming it automagically reflects the latest state on GitHub.

**Comment by Gadgetoid** [comment]
I've updated Pypi. Twice because I'm a fool.

It tends to track behind the GitHub codebase a little since code here might be a little bleeding edge/broken.
